/**
 * Billing Seeder — initial feature catalogue and plan definitions.
 *
 * ─── This file is a BOOTSTRAP, not configuration ──────────────────────────────
 * It populates MongoDB with a sensible starting catalogue. Once seeded, the
 * database is authoritative: change prices, limits, descriptions or active
 * status by editing the documents (Atlas UI, Compass, or an admin endpoint).
 * Do NOT edit this file to change live pricing — re-running the seeder is
 * idempotent and will not overwrite operator changes (see `upsertPlan`).
 *
 * Run with:  npm run seed:billing
 */

import { Feature, SubscriptionPlan } from '../models';
import { FEATURE_KEYS, PLAN_CODES, RC_ENTITLEMENTS } from '../constants';
import { planRepository } from '../repositories';

/**
 * Store product identifiers.
 *
 * These MUST match the product IDs created in Google Play Console (and later App
 * Store Connect / RevenueCat Web Billing). Override per-environment via env vars
 * so staging and production can point at different SKUs without a code change.
 */
const PRODUCT_IDS = {
  STANDARD_MONTHLY: process.env.PRODUCT_ID_STANDARD_MONTHLY || 'vedicscan_standard_monthly',
  STANDARD_YEARLY: process.env.PRODUCT_ID_STANDARD_YEARLY || 'vedicscan_standard_yearly',
  ADDON_PACK: process.env.PRODUCT_ID_ADDON_PACK || 'vedicscan_addon_pack',
};

/** The gateable capability catalogue. */
const FEATURES = [
  {
    key: FEATURE_KEYS.AI_CHAT,
    displayName: 'AI Chat Sessions',
    description: 'Conversations with the AI Vedic astrologer.',
    defaultPeriod: 'daily' as const,
    addonEligible: true,
  },
  {
    key: FEATURE_KEYS.KUNDALI_REPORT,
    displayName: 'Detailed Kundali Report',
    description: 'Full birth-chart analysis with a downloadable, shareable PDF.',
    defaultPeriod: 'monthly' as const,
    addonEligible: true,
  },
  {
    key: FEATURE_KEYS.KUNDALI_BASIC,
    displayName: 'Basic Kundali',
    description: 'Birth chart generation without the detailed PDF report.',
    defaultPeriod: 'lifetime' as const,
    addonEligible: false,
  },
  {
    key: FEATURE_KEYS.COMPATIBILITY_REPORT,
    displayName: 'Detailed Compatibility Report',
    description: 'Full compatibility analysis with a downloadable, shareable PDF.',
    defaultPeriod: 'monthly' as const,
    addonEligible: true,
  },
  {
    key: FEATURE_KEYS.COMPATIBILITY_BASIC,
    displayName: 'Basic Compatibility Match',
    description: 'Compatibility score and summary without the detailed PDF report.',
    defaultPeriod: 'lifetime' as const,
    addonEligible: false,
  },
  {
    key: FEATURE_KEYS.BABY_NAMING,
    displayName: 'Baby Naming',
    description: 'Astrologically aligned baby name suggestions.',
    defaultPeriod: 'monthly' as const,
    addonEligible: false,
  },
  {
    key: FEATURE_KEYS.RASHIFAL_NOTIFICATION,
    displayName: 'Daily Rashifal Notifications',
    description: 'Personalised daily horoscope push notifications.',
    defaultPeriod: 'daily' as const,
    addonEligible: false,
  },
];

/**
 * Plan definitions.
 *
 * Pricing note: `IN` covers India, `DEFAULT` is the rest-of-world fallback.
 * Adding a region later (e.g. `{ region: 'GB', currency: 'GBP', ... }`) needs no
 * code change — the resolver already falls back correctly for any region absent
 * from the list.
 *
 * Amounts are in MINOR units (paise/cents) to avoid floating-point drift.
 */
const PLANS = [
  {
    code: PLAN_CODES.FREE,
    displayName: 'Free',
    description: 'Get started with daily Rashifal and a first look at your charts.',
    kind: 'subscription' as const,
    billingInterval: 'lifetime' as const,
    storeProductIds: [],
    entitlements: [
      // Free users get ONE basic Kundali and ONE basic Compatibility, ever —
      // hence `lifetime`, which never resets. The detailed PDF report features
      // are absent entirely, so requireFeature() returns "feature_locked" and
      // the app can show an upgrade prompt rather than a quota message.
      { featureKey: FEATURE_KEYS.KUNDALI_BASIC, limit: 1, period: 'lifetime' as const },
      { featureKey: FEATURE_KEYS.COMPATIBILITY_BASIC, limit: 1, period: 'lifetime' as const },
      { featureKey: FEATURE_KEYS.RASHIFAL_NOTIFICATION, limit: -1, period: 'daily' as const },
    ],
    prices: [
      { region: 'IN', currency: 'INR', amountMinor: 0, displayPrice: '₹0' },
      { region: 'DEFAULT', currency: 'USD', amountMinor: 0, displayPrice: '$0' },
    ],
    expiresAtEndOfPurchaseDay: false,
    sortOrder: 0,
    // Per-plan AI tuning. Lives in metadata (not code) so response length,
    // context depth and retention can be tuned per tier without a redeploy.
    metadata: {
      maxWordsPerQuestion: 150,
      maxContextMessages: 4,
      maxCompletionTokens: 800,
      chatHistoryRetentionDays: 7,
    },
  },
  {
    code: PLAN_CODES.STANDARD_MONTHLY,
    displayName: 'Standard Monthly',
    description: 'Full access to AI chat, detailed reports and unlimited baby naming.',
    kind: 'subscription' as const,
    billingInterval: 'monthly' as const,
    revenueCatEntitlementId: RC_ENTITLEMENTS.STANDARD,
    storeProductIds: [PRODUCT_IDS.STANDARD_MONTHLY],
    entitlements: [
      { featureKey: FEATURE_KEYS.AI_CHAT, limit: 11, period: 'daily' as const },
      { featureKey: FEATURE_KEYS.KUNDALI_REPORT, limit: 5, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.COMPATIBILITY_REPORT, limit: 5, period: 'monthly' as const },
      // Paid plans also retain unmetered access to the basic variants.
      { featureKey: FEATURE_KEYS.KUNDALI_BASIC, limit: -1, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.COMPATIBILITY_BASIC, limit: -1, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.BABY_NAMING, limit: -1, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.RASHIFAL_NOTIFICATION, limit: -1, period: 'daily' as const },
    ],
    prices: [
      { region: 'IN', currency: 'INR', amountMinor: 29900, displayPrice: '₹299' },
      { region: 'DEFAULT', currency: 'USD', amountMinor: 900, displayPrice: '$9' },
    ],
    expiresAtEndOfPurchaseDay: false,
    sortOrder: 1,
    metadata: {
      maxWordsPerQuestion: 300,
      maxContextMessages: 10,
      maxCompletionTokens: 800,
      chatHistoryRetentionDays: 90,
    },
  },
  {
    code: PLAN_CODES.STANDARD_YEARLY,
    displayName: 'Standard Yearly',
    description: 'Everything in Standard, billed annually with fresh limits every month.',
    kind: 'subscription' as const,
    billingInterval: 'yearly' as const,
    revenueCatEntitlementId: RC_ENTITLEMENTS.STANDARD,
    storeProductIds: [PRODUCT_IDS.STANDARD_YEARLY],
    entitlements: [
      // Identical entitlements to the monthly plan, with the SAME daily/monthly
      // periods. That is precisely how a yearly subscriber receives fresh limits
      // every month for the whole year: the billing interval controls when the
      // store charges, while `period` controls when quotas reset. The two are
      // deliberately independent.
      { featureKey: FEATURE_KEYS.AI_CHAT, limit: 11, period: 'daily' as const },
      { featureKey: FEATURE_KEYS.KUNDALI_REPORT, limit: 5, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.COMPATIBILITY_REPORT, limit: 5, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.KUNDALI_BASIC, limit: -1, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.COMPATIBILITY_BASIC, limit: -1, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.BABY_NAMING, limit: -1, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.RASHIFAL_NOTIFICATION, limit: -1, period: 'daily' as const },
    ],
    prices: [
      { region: 'IN', currency: 'INR', amountMinor: 249900, displayPrice: '₹2,499' },
      { region: 'DEFAULT', currency: 'USD', amountMinor: 7900, displayPrice: '$79' },
    ],
    expiresAtEndOfPurchaseDay: false,
    sortOrder: 2,
    metadata: {
      maxWordsPerQuestion: 300,
      maxContextMessages: 10,
      maxCompletionTokens: 800,
      chatHistoryRetentionDays: 90,
    },
  },
  {
    code: PLAN_CODES.ADDON_PACK,
    displayName: 'Add-on Pack',
    description: 'A one-day boost: 5 extra AI chats, 1 Kundali report, 1 Compatibility report.',
    kind: 'one_time' as const,
    billingInterval: 'none' as const,
    storeProductIds: [PRODUCT_IDS.ADDON_PACK],
    entitlements: [
      // For a one-time pack, `limit` is the number of units granted (not a
      // recurring allowance) and `period` is unused — the pack's own expiry
      // governs its lifetime.
      { featureKey: FEATURE_KEYS.AI_CHAT, limit: 5, period: 'daily' as const },
      { featureKey: FEATURE_KEYS.KUNDALI_REPORT, limit: 1, period: 'monthly' as const },
      { featureKey: FEATURE_KEYS.COMPATIBILITY_REPORT, limit: 1, period: 'monthly' as const },
    ],
    prices: [
      { region: 'IN', currency: 'INR', amountMinor: 4900, displayPrice: '₹49' },
      { region: 'DEFAULT', currency: 'USD', amountMinor: 400, displayPrice: '$4' },
    ],
    // Valid only for the purchase day — expires at the next billing-day boundary,
    // NOT 24 hours after purchase.
    validForHours: null,
    expiresAtEndOfPurchaseDay: true,
    sortOrder: 3,
  },
];

/**
 * Seed features and plans.
 *
 * @param force  When true, overwrite existing documents with the definitions
 *               above. Destroys operator pricing changes — intended for local
 *               development and CI only. NEVER pass true against production.
 */
export async function seedBillingData(force = false): Promise<void> {
  console.log('[BillingSeed] Seeding feature catalogue...');

  for (const feature of FEATURES) {
    if (force) {
      await Feature.findOneAndUpdate({ key: feature.key }, { $set: feature }, { upsert: true });
    } else {
      // $setOnInsert leaves an existing document completely untouched, so a
      // re-run after an operator edited descriptions is safe.
      await Feature.findOneAndUpdate(
        { key: feature.key },
        { $setOnInsert: { ...feature, isActive: true } },
        { upsert: true, setDefaultsOnInsert: true }
      );
    }
  }
  console.log(`[BillingSeed] ${FEATURES.length} features ready.`);

  console.log('[BillingSeed] Seeding subscription plans...');
  for (const plan of PLANS) {
    if (force) {
      await SubscriptionPlan.findOneAndUpdate({ code: plan.code }, { $set: plan }, { upsert: true });
      console.log(`[BillingSeed]   ${plan.code} — overwritten`);
    } else {
      const existing = await SubscriptionPlan.findOne({ code: plan.code }).select('_id').exec();
      if (existing) {
        console.log(`[BillingSeed]   ${plan.code} — already exists, left unchanged`);
        continue;
      }
      await SubscriptionPlan.create({ ...plan, isActive: true });
      console.log(`[BillingSeed]   ${plan.code} — created`);
    }
  }

  planRepository.invalidate();
  console.log('[BillingSeed] Done.');
}
